#!/usr/bin/env python

import sys
import cPickle as pickle
import time

import theano as th
import numpy as np

import world
import feature
import utils

th.config.optimizer_verbose = True
th.config.allow_gc = False
th.config.optimizer = 'fast_compile'
th.config.mode = 'FAST_COMPILE'

epochs = 40

ys = [
        0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.30, 0.35, 0.40,
]

if __name__ == '__main__':
    robot_y = utils.scalar()
    robot_v = utils.scalar()

    w = world.dorsa(active=True, 100, 100)

    for y in ys:
        w.cars[1].data0['x0'] = [-0.13, y, math.pi/2., 1.]
        w.cars[1].reset()

        num_cars = len(w.cars)
        controls = [[] for i in range(num_cars)]
        states = [[] for i in range(num_cars)]
        beliefs = [[] for i in range(num_cars)]

        for t in range(epochs):
            print("t = ", t)
            for car in w.cars:
                car.control(0,0)
            for car, hist in zip(w.cars, controls):
                hist.append(car.u)
            for car in w.cars:
                car.move()
            for car, hist in zip(w.cars, states):
                hist.append(car.x)
            for car, hist in zip(w.cars, beliefs):
                if hasattr(car, 'log_ps'):
                    hist.append(np.asarray([np.exp(log_p.get_value()) for log_p in car.log_ps]))

        with open('data/%s-%d-%d.pickle'%("perturb-y", y, int(time.time())), 'w') as f:
            pickle.dump((controls, states, beliefs), f)

        for car in w.cars:
            car.reset()
