#!/usr/bin/env python

import sys
import cPickle as pickle
import time

import theano as th
import numpy as np

import world
import feature

th.config.optimizer_verbose = True
th.config.allow_gc = False
th.config.optimizer = 'fast_compile'
th.config.mode = 'FAST_COMPILE'

epochs = 32

@feature.feature
def left_lane(t, x, u):
    return -(x[0]+0.13)**2

if __name__ == '__main__':
    name = sys.argv[1]
    w = getattr(world, name)()
    num_cars = len(w.cars)
    controls = [[] for i in range(num_cars)]
    states = [[] for i in range(num_cars)]
    beliefs = [[] for i in range(num_cars)]

    for t in range(epochs):
        print("t = ", t)
        for car in w.cars:
            car.control(0,0)
        for car, hist in zip(w.cars, controls):
            hist.append(car.u)
        for car in w.cars:
            car.move()
        for car, hist in zip(w.cars, states):
            hist.append(car.x)
        for car, hist in zip(w.cars, beliefs):
            if hasattr(car, 'log_ps'):
                hist.append(np.asarray([np.exp(log_p.get_value()) for log_p in car.log_ps]))

    with open('data/%s-%d.pickle'%(name, int(time.time())), 'w') as f:
        pickle.dump((controls, states, beliefs), f)
